# opentrons platform appveyor config
#   Note: if build get stucks, you can use RDP to diagnose
#   https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

image: Visual Studio 2015

environment:
  # ensure Python 3.6 is first in path
  PATH: 'C:\Python36;C:\Python36\Scripts;%PATH%'
  # GNU make
  MAKE: C:\MinGW\bin\mingw32-make.exe
  # publish configuration
  OT_BUCKET_RUN_APP: opentrons-run-app
  OT_FOLDER_RUN_APP: builds
  OT_BUILD: '%APPVEYOR_BUILD_NUMBER%'
  OT_BRANCH: '%APPVEYOR_REPO_BRANCH%'

platform: x64

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  # read node version from the first line of .nvmrc
  - ps: $env:nodejs_version = (Get-Content -Path .nvmrc)[0]
  - ps: Install-Product node $env:nodejs_version x64
  # install dev dependencies
  - cmd: '%MAKE% install'

# do not run MSBuild
build: false

# do not run automatic test discovery
test: off

build_script:
  - cmd: '%MAKE% test'
  # build run app
  - cmd: '%MAKE% -C app-shell dist-win'

after_build:
  - ps: Get-ChildItem .\app-shell\dist\publish\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName RunApp}

deploy:
  - provider: S3
    access_key_id: $(AWS_ACCESS_KEY)
    secret_access_key: $(AWS_SECRET_KEY)
    bucket: $(OT_BUCKET_RUN_APP)
    folder: $(OT_FOLDER_RUN_APP)
    set_public: true
    artifact: RunApp
